add_prefix_space: true
allow_truncated_sentences: false
batch_size: 16
consecutive_masking: false
corpora: !!python/tuple
- aochildes
hidden_size: 256
include_punctuation: true
initializer_range: 0.02
intermediate_size: 1024
job_name: null
layer_norm_eps: 1.0e-05
leave_unmasked_prob: 0.0
leave_unmasked_prob_start: 0.0
load_from_checkpoint: none
lr: 0.0001
mask_pattern_size: 2
mask_probability: 0.15
max_num_tokens_in_sequence: 128
num_attention_heads: 8
num_epochs: 1
num_layers: 8
num_mask_patterns: 10
num_sentences_per_input: 1
num_warmup_steps: 24000
param_name: param_005
probabilistic_masking: true
project_path: /media/ludwig_data/BabyBERTa
random_token_prob: 0.1
sample_with_replacement: false
save_path: babyberta_runs/param_005/2021-06-11-20:14:00_num3/saves
score_with_mask: false
tokenizer: a-a-w-w-w-8192
training_order: original
weight_decay: 0.0
data_size: 5M