batch_size: 16
corpus_name: childes-20191206
embedding_dropout: 0.1
google_vocab_rule: inclusive
hidden_size: 256
intermediate_size: 1024
job_name: null
lr: 0.0001
num_attention_heads: 8
num_layers: 8
num_masked: 6
num_mlm_epochs: 1
param_name: param_002
project_path: /media/research_data/BabyBertSRL
save_path: param_002/2020-06-29-14:54:33_num8/saves
srl_interleaved: false
srl_probability: 1.0
vocab_size: 4000
