batch_size: 16
corpus_name: childes-20191206
embedding_dropout: 0.1
google_vocab_rule: inclusive
hidden_size: 256
intermediate_size: 1024
job_name: null
lr: 0.0001
num_attention_heads: 8
num_layers: 8
num_masked: 6
num_mlm_epochs: 1
param_name: param_004
project_path: /media/research_data/BabyBertSRL
save_path: param_004/2020-06-30-11:13:08_num9/saves
srl_interleaved: true
srl_probability: 1.0
vocab_size: 4000
